# Generated by Django 3.2.6 on 2021-10-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=20)),
                ('genero', models.CharField(choices=[('F', 'FEMENINO'), ('M', 'MASCULINO')], default='M', max_length=20)),
                ('tipo', models.CharField(choices=[('V', 'VIEJO'), ('N', 'NUEVO')], default='N', max_length=20)),
                ('seccion', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'B')], default='A', max_length=20)),
                ('datos', models.CharField(max_length=200)),
                ('relacion', models.CharField(max_length=200)),
            ],
        ),
    ]
