# Generated by Django 3.2.6 on 2021-10-02 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='datos',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='relacion',
        ),
    ]
