# Generated by Django 3.2.6 on 2021-10-29 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0002_auto_20211002_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='genero',
            field=models.CharField(choices=[('FEMENINO', 'FEMENINO'), ('MASCULINO', 'MASCULINO')], default='M', max_length=20),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='seccion',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=20),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='tipo',
            field=models.CharField(choices=[('VIEJO', 'VIEJO'), ('NUEVO', 'NUEVO')], default='N', max_length=20),
        ),
    ]
