# Generated by Django 3.2.6 on 2021-10-29 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0006_auto_20211028_2138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='periodo',
            old_name='fecha_de_final',
            new_name='hora_de_final',
        ),
        migrations.RenameField(
            model_name='periodo',
            old_name='fecha_de_inicio',
            new_name='hora_de_inicio',
        ),
        migrations.RemoveField(
            model_name='periodo',
            name='año',
        ),
        migrations.RemoveField(
            model_name='periodo',
            name='monto',
        ),
        migrations.RemoveField(
            model_name='periodo',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='salon',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='salon',
            name='nombre',
        ),
    ]
