# Generated by Django 3.2.6 on 2021-10-29 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maestro',
            name='genero',
            field=models.CharField(choices=[('FEMENINO', 'FEMENINO'), ('MASCULINO', 'MASCULINO')], default='M', max_length=20),
        ),
    ]
